name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/catcontainer && 
        docker image ls && docker push neytor/catcontainer

    - name: Build and push the Docker image with tag
      run: |
        docker build . --file Dockerfile --tag neytor/catcontainer:v.fe.40 && \
        docker image ls && docker push neytor/catcontainer:v.fe.40
      
    

